#! /usr/local/bin/ruby

require 'rubygems'
require 'lockfile'
require 'net/imap'
Lockfile('lock' , :retries => 0) do
  require File.dirname(__FILE__) + '/../config/boot'
  require File.dirname(__FILE__) + '/../config/environment'

  imap = Net::IMAP.new(AppConfig[:imap_server], AppConfig[:imap_port], true)
  imap.login(AppConfig[:imap_username], AppConfig[:imap_pwd])
  imap.select('INBOX')
  imap.search(["NOT", "DELETED"]).each do |message_id|
    email = imap.fetch(message_id, 'RFC822' )[0].attr['RFC822']
    parsed_mail = TMail::Mail.parse(email)
    unless parsed_mail.to.nil? # Spam
      begin
        MailFetcher.receive(parsed_mail)
      rescue MailFetcher::DisorderlyMailException
        imap.copy message_id, 'Disorderly'
      rescue
        imap.copy message_id, 'Failed'
      end
    end
    imap.store(message_id, "+FLAGS" , [:Deleted]) unless Rails.env == 'development'
  end

  imap.expunge
  imap.logout
  imap.disconnect
end

